baseURL = "https://v8v88v8v88.github.io"
languageCode = "en-us"
title = "V8V88V8V88's Personal Website"
theme = "lekh"

[params]
Name = "V8V88V8V88"
About = "We're not here because we're free. We're here because we're __not__ free. There's no escaping reason. No denying purpose. Because as we both know without purpose, we would not exist.<br/> Read more [here](https://matrix.fandom.com/wiki/Agent_Smith)"
Email = "agentsmith@thematrix.com"
Resume = "" # Add the filename with file extension.
PostLimit = 4 # Sets the number of posts to display on the front page
GoatCounterCode = ""

[[params.profiles]]
name = "GitHub"
url = "https://github.com/V8V88V8V88"

[[params.profiles]]
name = "Twitter"
url = "https://twitter.com/V8V88V8V88"

[[params.profiles]]
name = "Reddit"
url = "https://www.reddit.com/user/v8v88v8v88"

[[params.profiles]]
name = "Goodreads"
url = "https://www.goodreads.com/user/show/V8V88V8V88"

[[params.profiles]]
name = "YouTube"
url = "https://www.youtube.com/c/MagicalV8"

[[params.profiles]]
name = "LinkedIn"
url = "https://in.linkedin.com/in/vaibhav-pratap-singh-2a294a133"

[[params.profiles]]
name = "Amino"
url = "https://aminoapps.com/c/indianamino/page/user/v8v88v8v88-tm-doyouknowdawae/g0Rq_zpQixfQPYM802bYq08PMPQKZB2P3bxT3"
